---
- hosts: test
  tasks:
  - name: copy redis
    copy: "src=redis.tar.gz dest=/home/wboss/redis.tar.gz"
    become: true
    become_user: wboss

  - name: copy shell script
    copy: "src=install_redis.sh dest=/home/wboss/install_redis.sh mode=0777"
  - name: excute shell script
    command: bash /home/wboss/install_redis.sh